PinBoard/urls.py
from django.conf import (
    settings,
)
from django.conf.urls.static import (
    static,
)
from django.contrib import (
    admin,
)
from django.urls import (
    include,
    path,
    re_path,
)
from django.views.generic import (
    RedirectView,
)
from drf_yasg import (
    openapi,
)
from drf_yasg.views import (
    get_schema_view,
)
from rest_framework import (
    permissions,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="PinBoard API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("core.urls")),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "api/",
        include(
            [
                re_path("users/", include("users.urls")),
                re_path("", include("tasks.urls")),
            ]
        ),
    ),
    path(r"favicon.ico", RedirectView.as_view(url="/staticfiles/images/favicon.ico")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import (
    path,
)

from core.views import (
    IndexView,
    PinBoardView,
)
from tasks.views import (
    CreateEpic,
    CreateTask,
    EditEpic,
    EditTask,
)
from users.views import (
    NewAccount,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("pinboard", PinBoardView.as_view(), name="pin_board"),
    path("task/edit/<int:pk>", EditTask.as_view(), name="edit_task"),
    path("task/create/", CreateTask.as_view(), name="create_task"),
    path("epic/edit/<int:pk>", EditEpic.as_view(), name="edit_epic"),
    path("epic/create/", CreateEpic.as_view(), name="create_epic"),
    path("new_account/", NewAccount.as_view(), name="new_account"),
]

core/models.py
from django.db import (
    models,
)


class DatesModelMixin(models.Model):
    """
    Mixin adding creation and modification field to model.

    Additionally, models using this mixin will be sorted by created_date.
    """

    created_date = models.DateTimeField(editable=False, auto_now_add=True)
    modified_date = models.DateTimeField(editable=False, auto_now=True)

    class Meta:
        abstract = True
        ordering = ["-created_date"]
        get_latest_by = ["created_date"]

core/views.py
from django.views.generic import (
    TemplateView,
)

from tasks.models import (
    Task,
)


class IndexView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_anonymous:
            user_tasks = "user_tasks"
            user_epics = "user_epics"

            context[user_tasks] = self.request.user.tasks()
            task_search = self.request.GET.get("task_search", False)
            if task_search:
                context[user_tasks] = (
                    context[user_tasks].filter(title__contains=task_search).all()
                )

            context[user_epics] = self.request.user.epics()
            epic_search = self.request.GET.get("epic_search", False)
            if epic_search:
                context[user_epics] = (
                    context[user_epics].filter(title__contains=epic_search).all()
                )
        return context


class PinBoardView(TemplateView):
    template_name = "core/pin_board.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_anonymous:
            context["user_tasks_open"] = self.request.user.tasks(Task.StatusType.OPENED)
            context["user_tasks_inprogress"] = self.request.user.tasks(
                Task.StatusType.INPROGRES
            )
            context["user_tasks_done"] = self.request.user.tasks(Task.StatusType.DONE)
        return context

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/custom.css" %}>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_head %}
    {% endblock %}

</head>
<body>
{% block body %}

    {% if messages %}
        <div>
            <strong>Messages:</strong>
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'core:index' %}">PinBoard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:pin_board' %}">PinBoard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:create_task' %}">New Task</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:create_epic' %}">New Epic</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rest_framework:login' %}">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:new_account' %}">Create account</a>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <div class="p-1 mb-2 bg-dark text-white">
                        {{ user.username }}
                    </div>
                    <div class="p-1 mb-2 bg-dark text-white">
                        <a class="nav-link" href="{% url 'rest_framework:logout' %}?next={% url 'core:index' %}">LogOut</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        {% if user.is_authenticated %}
            {% block content %}
            {% endblock %}
        {% else %}
            Welcome Guest
            {% block new_account %}
            {% endblock %}
        {% endif %}
    </div>
{% endblock %}
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>User epics</h2>
            <form class="form-inline" method="GET" action="" >
                <input class="form-control" type="search" name="epic_search">
                <button class="btn btn-primary" type="submit"> Search </button>
            </form>
            {% include "tasks/epic_list.html" with epic_list=user_epics %}
        </div>
        <div class="col">
            <h2>User tasks</h2>
            <form class="form-inline" method="GET" action="" >
                <input class="form-control" type="search" name="task_search">
                <button class="btn btn-primary" type="submit"> Search </button>
            </form>
            {% include "tasks/task_list.html" with task_list=user_tasks %}
        </div>
    </div>
{% endblock %}

core/templates/core/pin_board.html
{% extends "core/base.html" %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>User opened tasks</h2>
            {% include "tasks/task_list.html" with task_list=user_tasks_open %}
        </div>
        <div class="col">
            <h2>User inprogress tasks</h2>
            {% include "tasks/task_list.html" with task_list=user_tasks_inprogress %}
        </div>
        <div class="col">
            <h2>User done tasks</h2>
            {% include "tasks/task_list.html" with task_list=user_tasks_done %}
        </div>
    </div>
{% endblock %}