PinBoard/urls.py
from django.conf import (
    settings,
)
from django.conf.urls.static import (
    static,
)
from django.contrib import (
    admin,
)
from django.urls import (
    include,
    path,
    re_path,
)
from django.views.generic import (
    RedirectView,
)
from drf_yasg import (
    openapi,
)
from drf_yasg.views import (
    get_schema_view,
)
from rest_framework import (
    permissions,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="PinBoard API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("core.urls")),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "api/",
        include(
            [
                re_path("users/", include("users.urls")),
                re_path("", include("tasks.urls")),
            ]
        ),
    ),
    path(r"favicon.ico", RedirectView.as_view(url="/staticfiles/images/favicon.ico")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import (
    path,
)

from core.views import (
    IndexView,
    PinBoardView,
)
from tasks.views import (
    CreateEpic,
    CreateTask,
    EditEpic,
    EditTask,
)
from users.views import (
    NewAccount,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("pinboard", PinBoardView.as_view(), name="pin_board"),
    path("task/edit/<int:pk>", EditTask.as_view(), name="edit_task"),
    path("task/create/", CreateTask.as_view(), name="create_task"),
    path("epic/edit/<int:pk>", EditEpic.as_view(), name="edit_epic"),
    path("epic/create/", CreateEpic.as_view(), name="create_epic"),
    path("new_account/", NewAccount.as_view(), name="new_account"),
]

tasks/urls.py
from django.urls import (
    re_path,
)
from rest_framework.routers import (
    DefaultRouter,
)

from tasks import (
    views,
)

app_name = "tasks"

router_v1 = DefaultRouter()
router_v1.register("tasks", views.TasksViewSet)
router_v1.register("epics", views.EpicViewSet)

urlpatterns = [
    re_path("epics/tasks", views.ListTaskApiView.as_view(), name="epic-tasks")
]

urlpatterns += router_v1.urls

tasks/models.py
from django.db import (
    models,
)

from core.models import (
    DatesModelMixin,
)


class Task(DatesModelMixin):
    """User task"""

    class StatusType(models.TextChoices):
        """Allowed statuses"""

        OPENED = "Opened"
        INPROGRES = "In Progress"
        DONE = "Done"

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="user_tasks"
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=StatusType.choices)
    epic = models.ForeignKey(
        "Epic", on_delete=models.DO_NOTHING, related_name="epic_tasks", null=True
    )


class Epic(DatesModelMixin):
    """
    Epic model

    Its a label for tasks.
    """

    user = models.ForeignKey(
        "users.User", on_delete=models.DO_NOTHING, related_name="user_epics"
    )
    title = models.CharField(max_length=100)

    def __str__(self):
        return str(self.title)

tasks/views.py
from django.shortcuts import (
    redirect,
)
from django_filters import (
    rest_framework as filters,
)
from rest_framework import (
    permissions,
)
from rest_framework.generics import (
    GenericAPIView,
    get_object_or_404,
)
from rest_framework.renderers import (
    TemplateHTMLRenderer,
)
from rest_framework.response import (
    Response,
)
from rest_framework.viewsets import (
    ModelViewSet,
)

from tasks.filtersets import (
    EpicFilter,
    TaskFilter,
)
from tasks.models import (
    Epic,
    Task,
)
from tasks.serializers import (
    EpicSerializer,
    NewTaskSerializer,
    TaskSerializer,
)


class TasksViewSet(ModelViewSet):
    """Operate on user tasks"""

    serializer_class = TaskSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    queryset = Task.objects.all()
    filter_backends = [filters.DjangoFilterBackend]
    filterset_class = TaskFilter

    def get_serializer_class(self):
        if self.action == "create":
            return NewTaskSerializer
        else:
            return super().get_serializer_class()

    def get_queryset(self):
        """Return user Tasks"""
        queryset = super().get_queryset()
        if not self.request.user.is_authenticated:
            return queryset.none()
        return queryset.filter(user=self.request.user).all()

    def perform_create(self, serializer):
        """Add current user to the serializer"""
        serializer.save(user=self.request.user)


class EpicViewSet(ModelViewSet):
    """Operate on user epics"""

    serializer_class = EpicSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    queryset = Epic.objects.all()
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = EpicFilter

    def get_queryset(self):
        """Return user Epics"""
        queryset = super().get_queryset()
        if not self.request.user.is_authenticated:
            return queryset.none()
        return queryset.filter(user=self.request.user).all()

    def perform_create(self, serializer):
        """Add current user to the serializer"""
        serializer.save(user=self.request.user)


class EditTask(GenericAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "tasks/edit_task.html"
    serializer_class = TaskSerializer
    swagger_schema = None

    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        serializer = self.get_serializer(task)
        return Response({"serializer": serializer, "task": task})

    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        serializer = self.get_serializer(task, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "task": task})
        serializer.save()
        return redirect("core:index")


class CreateTask(GenericAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "tasks/create_task.html"
    serializer_class = NewTaskSerializer
    swagger_schema = None

    def get(self, request):
        serializer = self.get_serializer()
        return Response({"serializer": serializer})

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer})
        serializer.save(user=self.request.user)
        return redirect("core:index")


class EditEpic(GenericAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "tasks/edit_epic.html"
    serializer_class = EpicSerializer
    swagger_schema = None

    def get(self, request, pk):
        epic = get_object_or_404(Epic, pk=pk)
        serializer = self.get_serializer(epic)
        return Response({"serializer": serializer, "epic": epic})

    def post(self, request, pk):
        epic = get_object_or_404(Epic, pk=pk)
        serializer = self.get_serializer(epic, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "epic": epic})
        serializer.save()
        return redirect("core:index")


class CreateEpic(GenericAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "tasks/create_epic.html"
    serializer_class = EpicSerializer
    swagger_schema = None

    def get(self, request):
        serializer = self.get_serializer()
        return Response({"serializer": serializer})

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer})
        serializer.save(user=self.request.user)
        return redirect("core:index")

tasks/templates/tasks/create_epic.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>New epic</h2>
    <form action="{% url 'core:create_epic' %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/create_task.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>New task</h2>
    <form action="{% url 'core:create_task' %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/edit_epic.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>Edit epic</h2>
    <form action="{% url 'core:edit_epic' pk=epic.id %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/edit_task.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>Edit task</h2>
    <form action="{% url 'core:edit_task' pk=task.id %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/epic_list.html
<div class="list-group">
    {% for epic in epic_list %}
        <a href="{% url 'core:edit_epic' pk=epic.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ epic.title }}</h5>
            </div>
            <p class="mb-1">{{ task.user }}</p>
        </a>
    {% endfor %}
</div>

tasks/templates/tasks/task.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>{% if id %} Edit {% else %} Create {% endif %} task</h2>
    <form action="{% url 'core:task_edit' pk=task.id %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/task_create.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>New task</h2>
    <form action="{% url 'core:task_create' %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/task_edit.html
{% extends "core/base.html" %}

{% load rest_framework %}

{% block content %}
    <h2>Edit task</h2>
    <form action="{% url 'core:task_edit' pk=task.id %}" method="POST">
            {% csrf_token %}
            {% render_form serializer %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

tasks/templates/tasks/task_list.html
<div class="list-group">
    {% for task in task_list %}
        <a href="{% url 'core:edit_task' pk=task.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ task.title }}</h5>
                <small>{{ task.status }}</small>
            </div>
            <p class="mb-1">{{ task.description }}</p>
            <small>Epic: {{ task.epic }}</small>
        </a>
    {% endfor %}
</div>